CREATE TYPE user_role AS ENUM ('admin','super_admin','system_admin');
CREATE TYPE user_status AS ENUM ('active','inactive','blocked');
CREATE TYPE subscription_type AS ENUM ('free','standard','pro');
CREATE TYPE company_status AS ENUM ('active','expired','suspended','deleted');
CREATE TYPE company_action_type AS ENUM (
  'created','updated','renewed','suspended','activated','deleted','document_updated'
);
CREATE TYPE response_status_type AS ENUM ('success','failed');
CREATE TYPE payment_status_type AS ENUM ('pending','paid','failed','refunded');
CREATE TYPE payment_mode_type AS ENUM ('cash','upi','bank','card','manual');
CREATE TYPE notification_type AS ENUM (
  'expiry','renewal','bug','system','company','billing'
);
CREATE TYPE bug_status_type AS ENUM ('todo','in_progress','done');

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    username VARCHAR(80) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role user_role NOT NULL DEFAULT 'admin',
    otp_code VARCHAR(10),
    otp_expiry TIMESTAMP,
    is_verified BOOLEAN DEFAULT FALSE,
    profile_image TEXT NULL,
    phone VARCHAR(30) NULL,
    status user_status DEFAULT 'active',
    created_by INT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE login_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(60),
    user_agent TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(180) NOT NULL,
    company_email VARCHAR(150) NOT NULL,
    contact VARCHAR(50),
    location VARCHAR(200),
    subscription_type subscription_type NOT NULL DEFAULT 'free',
    created_by INT NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    renewed_by INT NULL,
    renewed_on TIMESTAMP NULL,
    expiry_date TIMESTAMP NOT NULL,
    api_key VARCHAR(255) UNIQUE NOT NULL,
    endpoint VARCHAR(255) UNIQUE NOT NULL,
    document_path TEXT,
    notes TEXT NULL,
    status company_status DEFAULT 'active',
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (renewed_by) REFERENCES users(id)
);

CREATE TABLE company_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    action_type company_action_type NOT NULL,
    done_by INT NOT NULL,
    remarks TEXT,
    action_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (done_by) REFERENCES users(id)
);

CREATE TABLE models (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NULL,
    model_name VARCHAR(120) NOT NULL DEFAULT 'ollama',
    model_version VARCHAR(80),
    vector_db_path TEXT,
    embedding_model VARCHAR(120),
    prompt_template TEXT,
    temperature DECIMAL(3,2) DEFAULT 0.70,
    top_k INT DEFAULT 5,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE api_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    endpoint VARCHAR(255),
    request_ip VARCHAR(60),
    question TEXT,
    response_status response_status_type DEFAULT 'success',
    response_time_ms INT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE billing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL,
    plan_type subscription_type NOT NULL,
    amount DECIMAL(12,2) DEFAULT 0.00,
    billing_start DATE NOT NULL,
    billing_end DATE NOT NULL,
    payment_status payment_status_type DEFAULT 'pending',
    payment_mode payment_mode_type DEFAULT 'manual',
    invoice_no VARCHAR(100) UNIQUE NULL,
    created_by INT NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type notification_type DEFAULT 'system',
    is_read BOOLEAN DEFAULT FALSE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE bug_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    attachment_path TEXT NULL,
    reported_by INT NOT NULL,
    assigned_to INT NULL,
    status bug_status_type DEFAULT 'todo',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reported_by) REFERENCES users(id),
    FOREIGN KEY (assigned_to) REFERENCES users(id)
);

CREATE TABLE user_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    activity_name VARCHAR(255),
    activity_details TEXT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_company_expiry ON companies(expiry_date);
CREATE INDEX idx_company_status ON companies(status);
CREATE INDEX idx_user_role ON users(role);
CREATE INDEX idx_bug_status ON bug_reports(status);
CREATE INDEX idx_notification_user ON notifications(user_id);
CREATE INDEX idx_api_logs_company ON api_logs(company_id);

INSERT INTO users (
    full_name,
    username,
    email,
    password_hash,
    role,
    is_verified,
    status
)
VALUES (
    'Shaik Ahamed',
    'shaikahamed',
    'shaik.ahamed@tammina.com',
    '$2b$12$.rY064m712O1Km1xRdBAp.udbjIb9UEV8ni6DkL/04Jl0WpC2eLF.$2b$12$.rY064m712O1Km1xRdBAp.udbjIb9UEV8ni6DkL/04Jl0WpC2eLF.$2b$12$.rY064m712O1Km1xRdBAp.udbjIb9UEV8ni6DkL/04Jl0WpC2eLF.',
    'system_admin',
    TRUE,
    'active'
);